version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto8
    commands:
      - echo "Nothing to do in custom installation commands for now.."
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Nothing to do in pre_build phase for now.."
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    on-failure: ABORT
    commands:
      - echo Copying jar files to common directory
      - mkdir artifacts/
      - cp queue-request-handler/target/queue-request-handler.jar artifacts/
      - ls artifacts/
      - "aws s3 cp artifacts/* s3://sidharthramesh/codebuild/tokenizer_build/ --recursive"
artifacts:
  files:
    - '**/queue-request-handler.jar'
  name: artifact-name-in-buildspec
  discard-paths: yes
  s3-prefix: jarFiles